# Generated by Django 3.2.8 on 2021-10-06 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='supermarket',
            options={'verbose_name': 'Supermercado', 'verbose_name_plural': 'Supermercados'},
        ),
        migrations.AlterModelOptions(
            name='unit_of_measurement',
            options={'verbose_name': 'Unidade de Medida', 'verbose_name_plural': 'Unidades de Medidas'},
        ),
        migrations.RemoveField(
            model_name='supermarket',
            name='city',
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_of_measurement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unit_of_measurement', verbose_name='Unidade de Medida'),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='unit_of_measurement',
            name='initials',
            field=models.CharField(max_length=6, verbose_name='Sigla'),
        ),
        migrations.AlterField(
            model_name='unit_of_measurement',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
